### ISSUE TITLE
Question about MVS depth estimation

### ISSUE THREAD

**Issue by suvzzc** [Z-Pengcheng/MGS-SLAM#2]
Hello.
Great article. I have a question. May I ask the MVS depth estimation mentioned in your article, is its output relative depth or metric depth?

**Comment by Z-Pengcheng** [comment]
Relative depth. its scale is consistent with VO.

**Comment by suvzzc** [comment]
> Relative depth. its scale is consistent with VO.
Thanks for your quick reply.
So, is it possible to understand your MVS depth estimation method in this simple way. That is, you are expanding the sparse depth map of the VO into a dense depth map via MVS and still retaining the scaling calculated by the VO? Sort of like SFM's two-frame alignment operation to ensure one-to-many 3D points and 2D points. On this basis, successive relative depth maps can be used to construct subsequent 3D point clouds? Is it possible to understand it this way? I'm a first time learner and it may be a stupid question. I hope to get your answer.
Thanks.

**Comment by Z-Pengcheng** [comment]
Bold questioning is an important way to acquire knowledge, and it is not stupid. There is no problem with your understanding. We will also show more experiments in future versions to further demonstrate the superiority of MVS, such as in 3dgs geometric reconstruction. Thanks for your following.

**Comment by suvzzc** [comment]
> Bold questioning is an important way to acquire knowledge, and it is not stupid. There is no problem with your understanding. We will also show more experiments in future versions to further demonstrate the superiority of MVS, such as in 3dgs geometric reconstruction. Thanks for your following.
Thank you very much for your patience in answering my questions！
